export const DEBUG_TRACE_TYPES = Object.freeze({
	LOG: 'log',
	INFO: 'info',
	WARNING: 'warning',
	ERROR: 'error',
	DEBUG: 'debug',
});

export const DEBUG_BAR_CONFIG = Object.freeze({
	DEFAULT_LIMIT: 50,
	DEFAULT_OFFSET: 0,
	REFRESH_INTERVAL: 5000,
	MAX_SESSIONS_DISPLAY: 100,
	DEFAULT_TRACES_PAGE_SIZE: 50,
});

export const DEBUG_BAR_ERROR_MESSAGES = Object.freeze({
	TEMPLATE_NOT_FOUND: 'BIZPROCDESIGNER_DEBUG_TEMPLATE_NOT_FOUND',
	TRACES_LOAD_ERROR: 'BIZPROCDESIGNER_DEBUG_TRACES_LOAD_ERROR',
	CLEAR_ERROR: 'BIZPROCDESIGNER_DEBUG_CLEAR_ERROR',
	SESSIONS_LOAD_ERROR: 'BIZPROCDESIGNER_DEBUG_SESSIONS_LOAD_ERROR',
	INVALID_TEMPLATE_ID: 'BIZPROCDESIGNER_DEBUG_INVALID_TEMPLATE_ID',
	STATUS_CHECK_ERROR: 'BIZPROCDESIGNER_DEBUG_STATUS_CHECK_ERROR',
	TOGGLE_ERROR: 'BIZPROCDESIGNER_DEBUG_TOGGLE_ERROR',
});

export const DEBUG_BAR_LABELS = Object.freeze({
	TITLE: 'BIZPROCDESIGNER_DEBUG_BAR_TITLE',
	CLEAR_CONFIRM_MESSAGE: 'BIZPROCDESIGNER_DEBUG_BAR_CLEAR_CONFIRM_MESSAGE',
	CLEAR_CONFIRM_TITLE: 'BIZPROCDESIGNER_DEBUG_BAR_CLEAR_CONFIRM_TITLE',
	CLEAR_BUTTON: 'BIZPROCDESIGNER_DEBUG_BAR_CLEAR_BUTTON',
	CANCEL_BUTTON: 'BIZPROCDESIGNER_DEBUG_BAR_CANCEL_BUTTON',
	TRACES_LOADING: 'BIZPROCDESIGNER_DEBUG_BAR_TRACES_LOADING',
	TRACES_EMPTY: 'BIZPROCDESIGNER_DEBUG_BAR_TRACES_EMPTY',
	SESSIONS_EMPTY: 'BIZPROCDESIGNER_DEBUG_BAR_SESSIONS_EMPTY',
	BUTTON_ENABLE_TITLE: 'BIZPROCDESIGNER_DEBUG_BUTTON_ENABLE_TITLE',
	BUTTON_DISABLE_TITLE: 'BIZPROCDESIGNER_DEBUG_BUTTON_DISABLE_TITLE',
	LAYOUT_MAXIMIZE_TITLE: 'BIZPROCDESIGNER_DEBUG_BAR_LAYOUT_MAXIMIZE_TITLE',
	LAYOUT_MINIMIZE_TITLE: 'BIZPROCDESIGNER_DEBUG_BAR_LAYOUT_MINIMIZE_TITLE',
	LAYOUT_CLEAR_TITLE: 'BIZPROCDESIGNER_DEBUG_BAR_LAYOUT_CLEAR_TITLE',
	LAYOUT_CLOSE_TITLE: 'BIZPROCDESIGNER_DEBUG_BAR_LAYOUT_CLOSE_TITLE',
	SESSION_EXPAND_TITLE: 'BIZPROCDESIGNER_DEBUG_BAR_SESSION_EXPAND_TITLE',
	SESSION_COLLAPSE_TITLE: 'BIZPROCDESIGNER_DEBUG_BAR_SESSION_COLLAPSE_TITLE',
	SESSION_ACTIVE: 'BIZPROCDESIGNER_DEBUG_BAR_SESSION_ACTIVE',
	SESSION_FINISHED: 'BIZPROCDESIGNER_DEBUG_BAR_SESSION_FINISHED',
	LOAD_MORE_TRACES: 'BIZPROCDESIGNER_DEBUG_BAR_LOAD_MORE_TRACES',
});
